// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebProjeDeneme1.Data;

#nullable disable

namespace WebProjeDeneme1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebProjeDeneme1.Models.Kullanicilar.Uye", b =>
                {
                    b.Property<int>("UyeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UyeId"));

                    b.Property<bool>("AdminMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UyeId");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Personeller.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonelId"));

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("interval");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<string>("UzmanlikAlanlari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PersonelId");

                    b.HasIndex("SalonId");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Randevular.Randevu", b =>
                {
                    b.Property<int>("RandevuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RandevuId"));

                    b.Property<DateTime>("Gun")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IslemId")
                        .HasColumnType("integer");

                    b.Property<bool>("Onaylandi")
                        .HasColumnType("boolean");

                    b.Property<int>("PersonelId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("interval");

                    b.Property<int>("SalonId")
                        .HasColumnType("integer");

                    b.Property<int>("UyeId")
                        .HasColumnType("integer");

                    b.HasKey("RandevuId");

                    b.HasIndex("IslemId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SalonId");

                    b.HasIndex("UyeId");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Salonlar.Konum", b =>
                {
                    b.Property<int>("KonumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KonumId"));

                    b.Property<string>("KonumAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("KonumId");

                    b.ToTable("Konumlar");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Salonlar.Salon", b =>
                {
                    b.Property<int>("SalonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalonId"));

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("interval");

                    b.Property<int>("KonumId")
                        .HasColumnType("integer");

                    b.HasKey("SalonId");

                    b.HasIndex("KonumId");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Uzmanlik.UzmanlikAlani", b =>
                {
                    b.Property<int>("UzmanlikAlaniId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UzmanlikAlaniId"));

                    b.Property<string>("UzmanlikAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("UzmanlikAlaniId");

                    b.ToTable("UzmanlikAlanlari");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Uzmanlik.YapilabilenIslem", b =>
                {
                    b.Property<int>("YapilabilenIslemlerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("YapilabilenIslemlerId"));

                    b.Property<string>("IslemAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<TimeSpan>("IslemSuresi")
                        .HasColumnType("interval");

                    b.Property<decimal>("IslemUcreti")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UzmanlikAlaniId")
                        .HasColumnType("integer");

                    b.HasKey("YapilabilenIslemlerId");

                    b.HasIndex("UzmanlikAlaniId");

                    b.ToTable("YapilabilenIslemler");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Personeller.Personel", b =>
                {
                    b.HasOne("WebProjeDeneme1.Models.Salonlar.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Salon");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Randevular.Randevu", b =>
                {
                    b.HasOne("WebProjeDeneme1.Models.Uzmanlik.YapilabilenIslem", "Islem")
                        .WithMany()
                        .HasForeignKey("IslemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProjeDeneme1.Models.Personeller.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProjeDeneme1.Models.Salonlar.Salon", "Salon")
                        .WithMany()
                        .HasForeignKey("SalonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebProjeDeneme1.Models.Kullanicilar.Uye", "Uye")
                        .WithMany()
                        .HasForeignKey("UyeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Islem");

                    b.Navigation("Personel");

                    b.Navigation("Salon");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Salonlar.Salon", b =>
                {
                    b.HasOne("WebProjeDeneme1.Models.Salonlar.Konum", "Konum")
                        .WithMany()
                        .HasForeignKey("KonumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konum");
                });

            modelBuilder.Entity("WebProjeDeneme1.Models.Uzmanlik.YapilabilenIslem", b =>
                {
                    b.HasOne("WebProjeDeneme1.Models.Uzmanlik.UzmanlikAlani", "UzmanlikAlani")
                        .WithMany()
                        .HasForeignKey("UzmanlikAlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UzmanlikAlani");
                });
#pragma warning restore 612, 618
        }
    }
}
